---
label: Config
hide_body: true
is_partial: false
fields:
  - type: text
    name: title
    label: Title
    description: Site title
    config:
      required: true
  - type: text
    name: baseurl
    label: Base URL
    description: Serve the website from the given base URL
    hidden: true
  - type: text
    name: permalink
    label: Permalink
    description: 'The output path for your pages, posts, or collections.'
    hidden: true
    default: '/posts/:slug:output_ext'
  - type: text
    name: none
    label: None
    description: There are no config params
    hidden: true
    default: ''
  - type: field_group
    name: sass
    label: Sass
    hidden: true
    fields:
      - type: number
        name: indentWidth
        label: Indent Width
        description: >-
          Used to determine the number of spaces or tabs to be used for
          indentation.
        default: 4
      - type: select
        name: style
        label: Output Style
        description: Determines the output format of the final CSS style.
        default: nested
        config:
          source:
            type: custom
          options:
            - nested
            - expanded
            - compact
            - compressed
      - type: number
        name: precision
        label: Precision
        description: Used to determine how many digits after the decimal will be allowed.
        default: 10
  - type: list
    name: plugins
    label: Plugins
    hidden: true
  - type: list
    name: exclude
    label: Exclude
    description: Exclude directories and/or files from the conversion.
    hidden: true
